name: Test project
on: push
jobs: 
  test:
    runs_on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version:18
      - name: Install dependecies
        run: npm ci
      - name: Run test
        run: npm test